Feat/879 Create useTheme Hook
pluralsight/pando pull request #958
Opened 2023-01-09 02:22 UTC by nicholasmackey

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #879 

## What is the new behavior?

Adds a new useTheme hook to provide a way to manage custom themes.

## Other information

2023-01-11 15:28 UTC, caseybaggz commented
@nicholasmackey noticing this PR is getting a bit stale and wanted to check in. Did you mean to still have this in Draft mode? 

100% OK if you did. :)

2023-01-11 15:57 UTC, nicholasmackey commented
Hey @caseybaggz - I did intend on opening this up as a draft for my own review. Upon looking at, it I noticed that I did not include one of the requirements (Should accept a parameter for initial value.) 

If needed, I can delete this draft and reopen it once that requirement is met. I should be able to work on this more this afternoon/evening. ✌️

2023-01-11 16:38 UTC, caseybaggz commented
> Hey @caseybaggz - I did intend on opening this up as a draft for my own review. Upon looking at, it I noticed that I did not include one of the requirements (Should accept a parameter for initial value.)
> 
> If needed, I can delete this draft and reopen it once that requirement is met. I should be able to work on this more this afternoon/evening. ✌️

Ah, no worries. Work how you need. 100% was just checking in just in case it was accidentally left in the draft state. 😉

2023-01-12 04:18 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +  }
I'm not certain if this is how I should handle creating a "theme map." 
I'm open to ideas here.

2023-01-12 04:19 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +    return cachedTheme || themes.light
If all else fails, add "light" as a fallback.

2023-01-12 04:20 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +  const initialTheme = getInitialTheme()
Creating an intermediate variable may be unnecessary. 🤷 
I'm open to changing this.

2023-01-12 04:32 UTC, nicholasmackey commented on packages/react-utils/src/hooks/menu/utils.ts
> +}
Unsure if this formatting is up to standards. Please advise if not. 🙏

2023-01-12 04:37 UTC, nicholasmackey commented
> > Hey @caseybaggz - I did intend on opening this up as a draft for my own review. Upon looking at, it I noticed that I did not include one of the requirements (Should accept a parameter for initial value.)
> > If needed, I can delete this draft and reopen it once that requirement is met. I should be able to work on this more this afternoon/evening. ✌️
> 
> Ah, no worries. Work how you need. 100% was just checking in just in case it was accidentally left in the draft state. 😉

Thanks for your patience! This is now ready for review.

2023-01-12 15:07 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +  }
Alternatively, I thought about possibly handling it this way:

```typescript
  enum Themes {
    Light = 'light',
    Dark = 'dark',
  }

export function useTheme(preferredTheme?: 'light' | 'dark') {
  const themeMap = {
    [Themes.Light]: 'light',
    [Themes.Dark]: 'dark',
  }

  const getInitialTheme = () => {
    if (
      preferredTheme &&
      cachedTheme === null &&
      isThemeValid(preferredTheme)
    ) {
      return themeMap[preferredTheme]
    }
    return cachedTheme || themeMap[Themes.Light]
  }
  
```

Upon review, I decided that it may appear too verbose and difficult to read.

2023-01-12 15:27 UTC, caseybaggz requested changes
Good initial run! I would say ultimately, definitely overkill due to bringing in some JS practices into TS (remember, they are 2 different languages) and not fully knowing our library ecosystem (which is totally fine for a new contributor).

Looking forward to the updates.

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/menu/utils.test.ts
> +  it('should return false if the theme is an invalid string', () => {
I would say these last three are overkill since we are using TS, there is no need to have tests for them. Additionally, we have a strict rule to not ship `ts-expect-errors`. 😉

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/menu/utils.ts
> +export const isThemeValid = (theme: string) => {
Since we are using TS, we really don't even need this helper. I would just kill it. Additionally, for future ref you have this in the `menu` folder, but instead, something like this should be in either a general `utils` or maybe a `useTheme` folder.

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/menu/utils.ts
> +}
We use prettier which auto-formats, so there is no need to worry about that. 😸

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +export function useTheme(preferredTheme?: 'light' | 'dark') {
Let's move the params types out of the function since it's not scalable in case more themes are added. We can use a general `type Theme` declaration which would give the benefit of exporting for the API if a user needs it for some reason.

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +  }
I'm honestly not sure we really need a map yet, but am not opposed to having one - I would just move it out of the hook so we can export it and keep the hook small (performant).

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +  if (documentElement.getAttribute('ps-theme') === null && theme !== null) {
This should be inside an Effect, but we honestly don't need it. By nature of how hooks/React works, this is just duplicating the work and being overwritten by the Effect below.

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +  const getInitialTheme = () => {
In general, it's a good practice to keep hooks (and components) as small as possible with as less logic as possible to protect against unnecessary re-renders/commits. This function should definitely be outside of the hook and invoked immediately so the result is ready when the hook runs.

I also think it's a little overkill since we are using TS. In JS, you have to do checks like this, in TS, it's unnecessary due to the language being typed. 

Ultimately, meaning, this function should literally just get the localStorage value only. By nature, if there is no theme - our library will display `dark` as a fallback so we don't need most of this logic. 😉

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +    if (isThemeValid(theme)) {
Kill the check, but also, make sure you are referencing the docs on how [design-tokens work](https://design.pluralsight.com/docs/next/development/tokens/colors#themes). We don't use the localStorage key for the html tag.

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +      document.documentElement.setAttribute('ps-theme', theme)
```suggestion
document.documentElement.setAttribute('data-theme', theme)
```

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +  return { theme, toggleTheme }
Final thing, is very important regarding performance inside hooks. Since you are returning an Object that specifically uses a normal State, we need to return an memoized Object via `useMemo` which will ensure the hook doesn't force unnecessary commits when the theme state changes.

2023-01-12 15:27 UTC, caseybaggz commented on packages/react-utils/tests/hooks/useTheme.test.tsx
> +  test('should be light theme if the useTheme hook is provided an inital value that is invalid', () => {
Can kill this one.

2023-01-12 15:46 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +  }
Noted. ✌️

2023-01-12 15:47 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +    if (isThemeValid(theme)) {
Sure thing. I'll review that.

2023-01-12 15:50 UTC, nicholasmackey commented
> Good initial run! I would say ultimately, definitely overkill due to bringing in some JS practices into TS (remember, they are 2 different languages) and not fully knowing our library ecosystem (which is totally fine for a new contributor).
> 
> Looking forward to the updates.

Thanks for the in-depth explanations, @caseybaggz. I'll continue to work on working on your suggestions this afternoon/evening. ✌️

2023-01-17 18:21 UTC, caseybaggz commented
Just an update this week is the final week before we cut the RC release in case you want to get this feature in. No rush or pressure. We are grateful for your contribution in whatever time frame you can make it. 😉

2023-01-18 01:01 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +  return { theme, toggleTheme }
Understood. I'll change that.

2023-01-18 01:02 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +export function useTheme(preferredTheme?: 'light' | 'dark') {
So, we'd like it to be something along the following?

`export type Themes = 'dark' | 'light'`

2023-01-18 01:05 UTC, nicholasmackey commented on packages/react-utils/src/hooks/useTheme.ts
> +    if (isThemeValid(theme)) {
So, there may be some confusion on my part. 

Should I completely remove the line that sets the attribute on the `document` or update the hook with [your comment](https://github.com/pluralsight/pando/pull/958/files/daab804200f54118fcc46098e23e87fef7901bcf#r1068259350) below?

2023-01-18 15:06 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +    if (isThemeValid(theme)) {
Good question. Kill the condition (we don't need `isThemeValid`) and then, use the code below.

2023-01-18 15:16 UTC, caseybaggz requested changes
Just a couple fine tuning things and we are good to start testing in the sandbox link! 

If you want to try your hand at that, just click the sandbox link presented by CodeSandbox in the PR and try to use your API in a real world scenario. Once you have proven the API works in the sandbox, click the "share" button and post the link as a comment on the PR for validation and historical purposes. 😸

2023-01-18 15:16 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +  const [theme, setTheme] = useState(cachedTheme ?? preferredTheme)
Since this is a condition, it would be better for us to set it using the callback version which is a little more performant in this scenario.

```suggestion
  const [theme, setTheme] = useState(() => cachedTheme ?? preferredTheme)
```

2023-01-18 15:16 UTC, caseybaggz commented on packages/react-utils/src/hooks/useTheme.ts
> +  return { theme, toggleTheme }
All that's left here is to use `useMemo` to return the Object since it contains a state and callback to prevent unnecessary renders/commits.

[See example](https://github.com/pluralsight/pando/blob/main/packages/react-utils/src/hooks/useAutoFormatDate.ts#L38-L45)

2023-01-18 15:16 UTC, caseybaggz commented on packages/react-utils/tests/hooks/useTheme.test.tsx
> +  // Todo: getting act warnings
We don't like to ship `Todo` comments, so I would prefer we either get those in, or just kill the comment. We actually need to do this in the entire RU lib, so it's not a big deal to just kill the comment. Also a good next issue to work on if you want. 😉

2023-01-19 01:25 UTC, nicholasmackey commented
> Just a couple fine tuning things and we are good to start testing in the sandbox link!
> 
> If you want to try your hand at that, just click the sandbox link presented by CodeSandbox in the PR and try to use your API in a real world scenario. Once you have proven the API works in the sandbox, click the "share" button and post the link as a comment on the PR for validation and historical purposes. 😸

Sure thing. Give [this ](https://codesandbox.io/s/pando-usetheme-nywe4r?file=/src/hooks/useTheme.ts)a shot ✌️

2023-01-19 03:12 UTC, nicholasmackey commented
Here's the [CodeSandbox Example](https://codesandbox.io/s/pando-usetheme-nywe4r?file=/src/hooks/useTheme.ts) for the `useTheme` hook. 🤙

2023-01-19 17:02 UTC, caseybaggz reviewed
@nicholasmackey one last tiny test update to see if it resolves the act warnings. See #996 for more information.

2023-01-19 17:02 UTC, caseybaggz commented on packages/react-utils/tests/hooks/useTheme.test.tsx
> +    await user.click(button)
I think if we wrap all the click actions in `waitFor` it will resolve the act warnings.

Example:
```javascript
await waitFor(() => user.click(button))
```

2023-01-20 14:36 UTC, nicholasmackey commented on packages/react-utils/tests/hooks/useTheme.test.tsx
> +    await user.click(button)
Righteous. This appears to solve the warning. 🙏

2023-01-20 17:33 UTC, merged